Add ActionReplay cheat function
skylersaleh/SkyEmu pull request #299
Opened 2023-07-19 11:26 UTC by OFFTKP

The idea is that you add cheats through the UI, convert them to an array of uint32_t, and run each activated cheat using se_run_ar_cheat each frame. Here's a cheat you can hardcode to try if you want:

94000130 fdfc0002
1216398e 00000200
d2000000 00000000
94000130 fdfd0000
1216398e 00001c20
d2000000 00000000
94000130 000002dc
94000136 fffc0000
0224f90c 00000185
0224f910 030e8000
0224f914 00000000
0224f918 02ed8000
038090e0 eb9fe7c7
d2000000 00000000

Walk through walls
(Pokemon Black) (Hold L + A in game to activate, L + B to deactivate)

2023-07-19 20:07 UTC, OFFTKP commented
Things missing:
- Disable input when the edit/add cheat window is focused
- Better edit/add window layout
- Actually run the valid cheats from the cheats array
- Allow for pasting from the clipboard in the input inside the edit/add cheat window

2023-07-19 20:19 UTC, skylersaleh commented
It would be cool if we added in reading/writing of a cheat database too

2023-07-21 12:47 UTC, OFFTKP commented
Moved the AR code in nds.h (because it's different for every console) and also added the nds9_debug_read/write functions back, lmk if that's fine.

2023-07-25 19:32 UTC, skylersaleh requested changes
Hey could you fix up these items?

2023-07-25 19:32 UTC, skylersaleh commented on src/gba.h
> +          uint64_t decrypted=gba_decrypt_arv3(buffer[i+3] | ((uint64_t)buffer[i+2] << 32));
Can you add a buffer over run check here.

2023-07-25 19:32 UTC, skylersaleh commented on src/gba.h
> +          uint8_t data = buffer[i+2];
I think 0x10-0x14 need it for buffer[i+2] here too

2023-07-25 19:32 UTC, skylersaleh commented on src/gba.h
> +          uint8_t data_increment=(buffer[i+3]>>24)&0xFF;
Here too

2023-07-25 19:32 UTC, skylersaleh commented on src/gba.h
> +        case 0x80:{
Could you add a gs_button boolean variable at the top of the function and conditionals to implement the correct operation for these (and just hard code gs_button to true). That way we don't forget about the hack that we have here.

2023-07-25 19:32 UTC, skylersaleh commented on src/gba.h
> +        case 0x80:{
Same for all the other GS_button cases

2023-07-25 19:52 UTC, OFFTKP commented
> Hey could you fix up these items?

Done

2023-07-25 21:02 UTC, merged